// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProfile(arg1) {
  return window['go']['client']['Client']['AddProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['client']['Client']['DeleteProfile'](arg1);
}

export function GetProfiles() {
  return window['go']['client']['Client']['GetProfiles']();
}

export function LoadProfile(arg1) {
  return window['go']['client']['Client']['LoadProfile'](arg1);
}

export function UpdateCache(arg1) {
  return window['go']['client']['Client']['UpdateCache'](arg1);
}

export function UpdateProfile(arg1) {
  return window['go']['client']['Client']['UpdateProfile'](arg1);
}

export function WatchStream(arg1, arg2, arg3, arg4) {
  return window['go']['client']['Client']['WatchStream'](arg1, arg2, arg3, arg4);
}
