// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {client} from '../models';

export function AddProfile(arg1:models.Profile):Promise<void>;

export function DeleteProfile(arg1:number):Promise<void>;

export function GetProfiles():Promise<Array<models.Profile>>;

export function LoadProfile(arg1:models.Profile):Promise<client.XtreamData>;

export function UpdateCache(arg1:number):Promise<void>;

export function UpdateProfile(arg1:models.Profile):Promise<void>;

export function WatchStream(arg1:number,arg2:string,arg3:number,arg4:Array<number>):Promise<string>;
